
[font]
size = 13.0

[font.normal]
family = "JetBrainsMono Nerd Font"  # This is the correct name!
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[general]

# ~/.config/alacritty/alacritty.toml

# Import Catppuccin Mocha theme
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]

[terminal.shell]
program = "zellij"
args = ["attach", "--create", "default"]
