
[username]
show_always = false

[hostname]
ssh_only = true

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "on [$symbol$branch]($style) "

[git_status]
format = "([$all_status$ahead_behind]($style) )"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[aws]
disabled = true

[gcloud]
disabled = true

[kubernetes]
disabled = true

