add_newline = false

[username]
show_always = false

[hostname]
ssh_only = true

[directory]
truncation_length = 3
truncate_to_repo = true
truncation_symbol = "…/"

[git_branch]
format = "[$branch]($style) "

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "red"

[status]
disabled = false
format = '[\[$status\]](red) '

[cmd_duration]
min_time = 2000
format = '⏱ [$duration]($style) '
style = "yellow"

[python]
format = '[py:$version]($style) '
style = "blue"
disabled = true

[nodejs]
format = '[node:$version]($style) '
style = "green"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[time]
disabled = true # set to false if you want

[jobs]
symbol = "⚙️"
number_threshold = 1
