matches:
  - trigger: ";ae"
    replace: "ä"
  - trigger: ";oe"
    replace: "ö"
  - trigger: ";ue"
    replace: "ü"
  - trigger: ";Ae"
    replace: "Ä"
  - trigger: ";Oe"
    replace: "Ö"
  - trigger: ";Ue"
    replace: "Ü"
  - trigger: ";sz"
    replace: "ß"
